-- 1 俊辑  30  青俊 措茄 火涝 角菩
--ORA-01400: cannot insert NULL into ("JAVA01"."BOARD_REP"."RNO")
--青 1
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (2,'sdklfnasnf','lee');
--青 2
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'dgaj','kim');
--青 3
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (9,'osdgh','choi');
--青 4
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (4,'sagsd','lee');
--青 5
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (5,'gsg','kim');
--青 6
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (5,'gsgas','choi');
--青 7
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (10,'gsg','lee');
--青 8
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'sdgsdag','kim');
--青 9
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (2,'asgsdg','choi');
--青 10
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (3,'dgdas','lee');
--青 11
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (3,'ashfj','kim');
--青 12
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'ashfj','choi');
--青 13
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (9,'ashfj','lee');
--青 14
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (3,'ashfj','kim');
--青 15
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (10,'ashfj','choi');
--青 16
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (6,'ashfj','lee');
--青 17
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (8,'ashfj','kim');
--青 18
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (4,'ashfj','choi');
--青 19
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (3,'ashfj','lee');
--青 20
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (1,'ashfj','kim');
--青 21
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (8,'ashfj','choi');
--青 22
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (10,'ashfj','lee');
--青 23
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'ashfj','kim');
--青 24
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (4,'ashfj','choi');
--青 25
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'ashfj','lee');
--青 26
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (7,'ashfj','kim');
--青 27
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (6,'ashfj','choi');
--青 28
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (10,'ashfj','lee');
--青 29
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (8,'ashfj','kim');
--青 30
INSERT INTO BOARD_REP (NO, CONTENT, WRITER) VALUES (3,'ashfj','choi');
